#!/usr/bin/env bash
# Check if an IP address argument is provided

if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Get the IP address from the command line argument
ip_address="$1"

# Perform the ping and store the results in a variable
ping_result=$(ping -c 5 "$ip_address")

# Display the ping results
echo "$ping_result"
