#!/usr/bin/env bash
# This script displays the PID and process name of processes containing the word "bash" using awk.

# Get the process list using 'awk' and filter lines containing the word "bash"
# Print the PID (2nd field) and the process name (11th field) separated by a space
ps -e -o pid,cmd | awk '/bash/ && !/awk/ { print $1, $2 }'
