#!/usr/bin/env bash
# This script displays lines containing the word "bash" from the process list.

# shellcheck disable=SC2009
# Use 'ps' and 'grep' to filter lines containing the word "bash" and exclude the script itself
ps aux | grep bash | grep -v grep
