#!/usr/bin/env bash
# This script displays lines containing the word "bash" and filters out the script itself.

# shellcheck disable=SC2009
# Use 'ps' and 'grep' to filter lines containing the word "bash" and exclude the script itself
# Use 'grep -v' to filter out lines containing the script name
ps -ef | grep "[b]ash"
