#!/usr/bin/env bash
# Display user information from /etc/passwd using the while loop and IFS

# Use a while loop to read the file line by line
while IFS=: read -r username _ uid gid info home shell; do
    # Extract user information from the "info" field
    user_info=$(echo "$info" | awk -F, '{print $5}')
    passcode=$(echo "$info" | awk -F, '{print $6}')
    
    # Display the user information in the specified format
    echo "The user $username is part of the $gid gang, lives in $home, and rides $shell."
    echo "USER ID's place is protected by the passcode $passcode, more info about the user here: $user_info"
    echo
done < /etc/passwd
