#!/usr/bin/env bash
# Check if the script is running inside a Docker container

if [ -f "/.dockerenv" ]; then
    # Modify /etc/hosts to change localhost and facebook.com resolutions
    echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
    echo "Hosts file updated. You may need to restart networking or the container for changes to take effect."
else
    echo "This script should be run inside a Docker container. It will modify the hosts file of the container."
fi
